# fly.toml app configuration file generated for hr-os-f5mozg on 2026-05-12T15:21:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hr-os-f5mozg'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  HR_DB_PATH = '/data/hr-os.db'
  HR_SKIP_SEED = '1'
  NODE_ENV = 'production'
  PORT = '3010'
  UPLOADS_DIR = '/data/uploads'

[[mounts]]
  source = 'hr_os_data'
  destination = '/data'

[http_service]
  internal_port = 3010
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '20s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  size = 'shared-cpu-2x'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
