import { describe, it, expect, beforeEach } from "vitest";
import { computeExpectedReminders, regenerateReminders } from "@/lib/reminder-generator";
import { db } from "@/lib/db";

describe("reminder generator", () => {
  // Use a fixed "today" so the seed dates produce stable results
  const fixedNow = new Date("2026-05-10T00:00:00Z");

  it("generates 在留カード reminders for employees with zairyu_expiry within 90 days", () => {
    const all = computeExpectedReminders(fixedNow);
    const zairyu = all.filter((r) => r.category === "在留カード期限");
    // From seed: e3=2026-06-08 (~30d), e4=2025-12-22 (past), e5=2027-04-10 (>90d, skip),
    // e8=2026-05-30 (~20d), e9=2025-11-15 (past), e13=2026-07-20 (~70d), e15=2025-11-30 (past)
    expect(zairyu.length).toBeGreaterThan(0);
    // e5 (2027-04-10) should NOT appear — over 90 days
    expect(zairyu.find((r) => r.targetId === "e5")).toBeUndefined();
    // e3 should be critical (within 30 days)
    const e3 = zairyu.find((r) => r.targetId === "e3");
    expect(e3?.severity).toBe("critical");
    // All should have stable dedup keys
    expect(zairyu.every((r) => r.dedupKey.startsWith("zairyu:"))).toBe(true);
  });

  it("generates 試用期間終了 reminders for active probation employees", () => {
    const all = computeExpectedReminders(fixedNow);
    const probation = all.filter((r) => r.category === "試用期間終了");
    // Seed has 試用期間 employees with various probation_end dates
    // e4 (2025-07-14, past) and e5 (2025-09-30, past) — both > 7 days past, should be filtered out
    // e9 (2025-08-31, past) — also > 7 days past, filtered out
    // None of the seeded probation employees have probation_end within the [-7, +30] window from 2026-05-10
    // So probation reminders should be empty for this fixed date
    expect(probation.length).toBe(0);
  });

  it("generates 書類未提出 / 差戻し for active onboarding cases", () => {
    const all = computeExpectedReminders(fixedNow);
    const docMissing = all.filter((r) => r.category === "書類未提出" || r.category === "源泉徴収票未提出");
    const docReject = all.filter((r) => r.category === "書類差戻し");
    expect(docMissing.length).toBeGreaterThan(0);
    expect(docReject.length).toBeGreaterThan(0);
    // Lim's case (o5) is 完了 — should NOT generate
    expect(docMissing.find((r) => r.targetId.startsWith("o5:"))).toBeUndefined();
    // dedup keys
    expect(docMissing.every((r) => r.dedupKey.startsWith("doc_missing:"))).toBe(true);
    expect(docReject.every((r) => r.dedupKey.startsWith("doc_reject:"))).toBe(true);
  });

  it("regenerateReminders writes auto_generated rows and preserves handled state across runs", () => {
    // First run
    const r1 = regenerateReminders("test");
    expect(r1.generated).toBeGreaterThan(0);

    // Find an auto-generated reminder, mark it handled
    const all1: any[] = db.reminders().filter((r: any) => r.autoGenerated === 1);
    expect(all1.length).toBeGreaterThan(0);
    const target = all1[0];
    db.markReminderHandled(target.id, "test-user");

    // Second run — same expected set, but handled state should persist
    const r2 = regenerateReminders("test");
    expect(r2.generated).toBe(r1.generated);
    expect(r2.updated).toBeGreaterThanOrEqual(1);

    // The new reminder with the same dedup_key should be handled
    const after: any[] = db.reminders().filter((r: any) => r.autoGenerated === 1);
    const sameDedup = after.find((r) => r.dedupKey === target.dedupKey);
    expect(sameDedup).toBeTruthy();
    expect(sameDedup.handledAt).toBeTruthy();
    expect(sameDedup.handledBy).toBe("test-user");
  });

  it("does not duplicate seed reminders (auto_generated = 0 untouched)", () => {
    const seedBefore: any[] = db.reminders().filter((r: any) => r.autoGenerated === 0);
    regenerateReminders("test");
    const seedAfter: any[] = db.reminders().filter((r: any) => r.autoGenerated === 0);
    expect(seedAfter.length).toBe(seedBefore.length);
  });
});
