"use client";
import { Card, CardHeader, Badge, Button } from "@/components/ui";
import { useState, useTransition } from "react";
import { IdCard, Clock, FileX, AlertTriangle, FileQuestion, Receipt, Check, Undo2 } from "lucide-react";
import clsx from "clsx";
import { setReminderHandled } from "@/lib/actions";
import { useRouter } from "next/navigation";
import Link from "next/link";

const cats = [
  { code: "all", label: "すべて", icon: AlertTriangle },
  { code: "在留カード期限", label: "在留カード期限", icon: IdCard },
  { code: "試用期間終了", label: "試用期間終了", icon: Clock },
  { code: "雇用契約終了", label: "雇用契約終了", icon: FileQuestion },
  { code: "書類未提出", label: "書類未提出", icon: FileX },
  { code: "書類差戻し", label: "書類差戻し", icon: AlertTriangle },
  { code: "源泉徴収票未提出", label: "源泉徴収票未提出", icon: Receipt },
];

const sevTone: any = { critical: "rose", warn: "amber", info: "blue" };
const sevLabel: any = { critical: "緊急", warn: "要注意", info: "通知" };

export default function RemindersClient({ reminders }: { reminders: any[] }) {
  const router = useRouter();
  const [pending, start] = useTransition();
  const [filter, setFilter] = useState("all");
  const [showHandled, setShowHandled] = useState(false);

  const visibleByCat = filter === "all" ? reminders : reminders.filter((r) => r.category === filter);
  const pendingList = visibleByCat.filter((r) => !r.handledAt);
  const handledList = visibleByCat.filter((r) => r.handledAt);

  const counts = cats.map((c) => ({
    ...c,
    count: c.code === "all"
      ? reminders.filter((r) => !r.handledAt).length
      : reminders.filter((r) => r.category === c.code && !r.handledAt).length,
  }));

  const toggle = (id: string, handled: boolean) => {
    start(async () => {
      try { await setReminderHandled(id, handled); router.refresh(); }
      catch (e) { console.error(e); }
    });
  };

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-7 gap-3">
        {counts.map((c) => {
          const Icon = c.icon;
          const active = filter === c.code;
          return (
            <button
              key={c.code}
              onClick={() => setFilter(c.code)}
              className={clsx(
                "p-3 rounded-xl text-left border transition-all",
                active ? "bg-brand-50 border-brand-300 shadow-sm" : "bg-white border-slate-200 hover:border-slate-300"
              )}
            >
              <Icon size={18} className={active ? "text-brand-600" : "text-slate-500"} />
              <div className="mt-2 text-xs text-slate-500 leading-tight">{c.label}</div>
              <div className="text-xl font-bold mt-1">{c.count}<span className="text-xs text-slate-400 ml-1">未対応</span></div>
            </button>
          );
        })}
      </div>

      <Card>
        <CardHeader
          title={`未対応（${pendingList.length}件）`}
          subtitle="対応する対応が必要な通知"
          right={pending && <span className="text-xs text-brand-600">保存中...</span>}
        />
        <div className="divide-y divide-slate-100">
          {pendingList.length === 0 && (
            <div className="p-8 text-center text-sm text-slate-400">未対応の通知はありません 🎉</div>
          )}
          {pendingList.map((r) => (
            <div key={r.id} className="p-4 flex items-start gap-4 hover:bg-slate-50">
              <div
                className={clsx(
                  "w-2 h-2 rounded-full mt-2 shrink-0",
                  r.severity === "critical" && "bg-rose-500",
                  r.severity === "warn" && "bg-amber-500",
                  r.severity === "info" && "bg-blue-500"
                )}
              />
              <div className="flex-1">
                <div className="flex items-center gap-2 flex-wrap">
                  <Badge tone={sevTone[r.severity]}>{sevLabel[r.severity]}</Badge>
                  <Badge tone="slate">{r.category}</Badge>
                  {r.autoGenerated === 1 && <Badge tone="violet" size="xs">自動</Badge>}
                  <span className="text-xs text-slate-500">{r.schoolName}</span>
                  <span className="ml-auto text-xs text-slate-400">{r.triggerDate}</span>
                </div>
                <div className="mt-1.5 font-medium text-sm text-slate-800">{r.title}</div>
                <div className="text-xs text-slate-500 mt-0.5">{r.detail}</div>
              </div>
              <div className="flex flex-col gap-1.5 shrink-0">
                {r.category === "試用期間終了" && r.targetType === "employee" && r.targetId && (
                  <Link
                    href={`/performance/profiles/${r.targetId}?newReview=1&type=${encodeURIComponent("試用期間評価")}&fromReminder=${r.id}`}
                    className="inline-flex items-center justify-center gap-1 px-3 py-1.5 text-xs bg-brand-600 text-white rounded-lg hover:bg-brand-700 whitespace-nowrap"
                  >
                    📈 評価を開始
                  </Link>
                )}
                <Button size="sm" variant="secondary" onClick={() => toggle(r.id, true)} disabled={pending}>
                  <Check size={14} />対応する
                </Button>
              </div>
            </div>
          ))}
        </div>
      </Card>

      <Card>
        <CardHeader
          title={`対応済み（${handledList.length}件）`}
          right={
            <button onClick={() => setShowHandled(!showHandled)} className="text-xs text-brand-600 hover:underline">
              {showHandled ? "閉じる" : "開く"}
            </button>
          }
        />
        {showHandled && (
          <div className="divide-y divide-slate-100">
            {handledList.length === 0 && (
              <div className="p-6 text-center text-xs text-slate-400">まだ対応済みの通知はありません</div>
            )}
            {handledList.map((r) => (
              <div key={r.id} className="p-4 flex items-start gap-4 opacity-60">
                <div className="w-2 h-2 rounded-full mt-2 shrink-0 bg-emerald-400" />
                <div className="flex-1">
                  <div className="flex items-center gap-2 flex-wrap">
                    <Badge tone="emerald">対応済</Badge>
                    <Badge tone="slate">{r.category}</Badge>
                    <span className="text-xs text-slate-500">{r.schoolName}</span>
                    <span className="ml-auto text-xs text-slate-400">対応者：{r.handledBy} ／ {r.handledAt?.slice(0,10)}</span>
                  </div>
                  <div className="mt-1.5 text-sm line-through text-slate-600">{r.title}</div>
                </div>
                <Button size="sm" variant="secondary" onClick={() => toggle(r.id, false)} disabled={pending}>
                  <Undo2 size={14} />未対応に戻す
                </Button>
              </div>
            ))}
          </div>
        )}
      </Card>
    </div>
  );
}
